export enum PermissionEnum {
  // EMPLEADOS
  CREATE_EMPLOYEE = "CREATE_EMPLOYEE",
  EDIT_EMPLOYEE = "EDIT_EMPLOYEE",
  DELETE_EMPLOYEE = "DELETE_EMPLOYEE",
  MANAGE_EMPLOYEE_ROLES = "MANAGE_EMPLOYEE_ROLES",

  // PRODUCTOS
  CREATE_PRODUCT = "CREATE_PRODUCT",
  EDIT_PRODUCT = "EDIT_PRODUCT",
  DELETE_PRODUCT = "DELETE_PRODUCT",
  MANAGE_PRODUCTS = "MANAGE_PRODUCTS",
  MANAGE_STOCK = "MANAGE_STOCK",

  // MENÚ / SECCIONES
  CREATE_MENU_SECTION = "CREATE_MENU_SECTION",
  EDIT_MENU_SECTION = "EDIT_MENU_SECTION",
  DELETE_MENU_SECTION = "DELETE_MENU_SECTION",
  MANAGE_MENU = "MANAGE_MENU",

  // NEGOCIO
  EDIT_BUSINESS = "EDIT_BUSINESS",
  DELETE_BUSINESS = "DELETE_BUSINESS",
  VIEW_DASHBOARD = "VIEW_DASHBOARD",
  VIEW_REPORTS = "VIEW_REPORTS",
  MANAGE_BUSINESS_SETTINGS = "MANAGE_BUSINESS_SETTINGS",
  MANAGE_DELIVERY_ZONES = "MANAGE_DELIVERY_ZONES",

  // PEDIDOS
  VIEW_ORDERS = "VIEW_ORDERS",
  CREATE_ORDER = "CREATE_ORDER",
  EDIT_ORDER = "EDIT_ORDER",
  CANCEL_ORDER = "CANCEL_ORDER",
  PROCESS_ORDER = "PROCESS_ORDER",
  DELIVER_ORDER = "DELIVER_ORDER",
  COMPLETE_ORDER = "COMPLETE_ORDER",

  // CAJAS
  VIEW_CASH_REGISTERS = "VIEW_CASH_REGISTERS",
  CREATE_CASH_REGISTER = "CREATE_CASH_REGISTER",
  EDIT_CASH_REGISTER = "EDIT_CASH_REGISTER",
  MANAGE_CASH_REGISTERS = "MANAGE_CASH_REGISTERS",
  OPEN_CASH_REGISTER = "OPEN_CASH_REGISTER",
  CLOSE_CASH_REGISTER = "CLOSE_CASH_REGISTER",
  VIEW_CASH_REGISTER_HISTORY = "VIEW_CASH_REGISTER_HISTORY",

  // TESORERÍA
  VIEW_TREASURY = "VIEW_TREASURY",
  CREATE_TREASURY_ACCOUNT = "CREATE_TREASURY_ACCOUNT",
  EDIT_TREASURY_ACCOUNT = "EDIT_TREASURY_ACCOUNT",
  MANAGE_TREASURY_ACCOUNTS = "MANAGE_TREASURY_ACCOUNTS",
  CREATE_FINANCIAL_MOVEMENT = "CREATE_FINANCIAL_MOVEMENT",
  VIEW_FINANCIAL_MOVEMENTS = "VIEW_FINANCIAL_MOVEMENTS",
  CREATE_INTERNAL_TRANSFER = "CREATE_INTERNAL_TRANSFER",

  // CLIENTES
  VIEW_CUSTOMERS = "VIEW_CUSTOMERS",
  CREATE_CUSTOMER = "CREATE_CUSTOMER",
  EDIT_CUSTOMER = "EDIT_CUSTOMER",

  // PAGOS
  MANAGE_PAYMENT_METHODS = "MANAGE_PAYMENT_METHODS",
}