export enum InventoryMovementReason {
  INITIAL_ADJUSTMENT = "INITIAL_ADJUSTMENT",
  MANUAL_ADJUSTMENT = "MANUAL_ADJUSTMENT",
  TRANSFER = "TRANSFER",
  CONSUMPTION = "CONSUMPTION",
  PRODUCTION = "PRODUCTION",
  RECEIPT = "RECEIPT",
  WASTE = "WASTE",
  EXPIRED = "EXPIRED",
}